### ISSUE TITLE
String.format()

### ISSUE THREAD

**Issue by melchior-by** [cyborg-shop/cucumber-training#1]
https://github.com/cyborg-shop/cucumber-training/blob/02844fb3beca6b86ad24eb67469b93d39c299596/src/main/java/pages/ResultPage.java#L16

**Comment by cyborg-shop** [comment]
> https://github.com/cyborg-shop/cucumber-training/blob/02844fb3beca6b86ad24eb67469b93d39c299596/src/main/java/pages/ResultPage.java#L16

Done!
