### ISSUE TITLE
Plz delete IDE files, use .gitignore file to remove them

### ISSUE THREAD

**Issue by melchior-by** [cyborg-shop/cucumber-training#2]
https://github.com/cyborg-shop/cucumber-training/blob/02844fb3beca6b86ad24eb67469b93d39c299596/cucumber-training.iml#L1

**Comment by cyborg-shop** [comment]
> https://github.com/cyborg-shop/cucumber-training/blob/02844fb3beca6b86ad24eb67469b93d39c299596/cucumber-training.iml#L1

Done!
